### ISSUE TITLE
Error: Oops, an error occurred! Code: 202201272208037d678e00

### ISSUE THREAD

**Issue by jantma2** [cdaecke/md_eventmgt_frontend#1]
I'm still very new to Typo3, so it might be possible that simply did something wrong.
I tried to follow the steps of the manual and struggled a bit with this statement:
"Select a storage page in the plugin-tab in the field Record Storage Page"

What does this exactly mean and does some wrong setup of this "record storeage page" lead to the error message?

**Comment by cdaecke** [comment]
The `Record Storage Page` is the page, where new records will be stored. You will find it with the following steps:

- Edit plugin
- Switch to `Plugin` tab
- At the bottom of the form you will see the field `Record Storage Page`.
- Choose the page, where you want to store new events

I am not sure, but it could well be, that the error message appears, if you create a new event and leave the field `Price` empty. Try to set some value for this field. If you still get this error, please have a look into the error log of TYPO3 (`typo3temp/var/log/...` for non composer and `var/log/...` for composer setup). Search for the error code there, and paste the error here.

**Comment by jantma2** [comment]
Thanks for your help - the extension is now working.
You're right there is a bug inside that one have to enter a value into the "price" field.
