### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by Hasan-Shaker** [cdaecke/md_eventmgt_frontend#2]
What's the strategy in place? Is there active effort being dedicated to it?

With version 12, there have been numerous alterations to the TypoScript handling. How will these changes impact the ease of updates?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
+1 for the continuation of this extension

**Comment by Hasan-Shaker** [comment]
Hy,
That's good for now. I can close this issues.

**Comment by cdaecke** [comment]
Version 2.0.0 is released, which is compatible with TYPO3 v12.
